### ISSUE TITLE
Not working and Error occurred when try to review cards

### ISSUE THREAD

**Issue by rogerfan48** [zacharied/anki-content-injector#7]
### The error messages are as below. I don't know why it cannot work since I have followed the instructions.
ps. I have added "_global.css" in "collection.media", and it just couldn't work.

```Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.4
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-22 22:56:08
Add-ons possibly involved: ⁨Content Injector⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "aqt.overview", line 92, in _linkHandler
  File "aqt.main", line 673, in moveToState
  File "aqt.main", line 694, in _reviewState
  File "aqt.reviewer", line 150, in show
  File "aqt.reviewer", line 170, in refresh_if_needed
  File "aqt.reviewer", line 233, in nextCard
  File "aqt.reviewer", line 354, in _showQuestion
  File "aqt.hooks_gen", line 1175, in __call__
  File "anki.hooks", line 45, in runFilter
  File "/Users/roger_fan/Library/Application Support/Anki2/addons21/166455199/__init__.py", line 62, in injectContent
    with open(f, 'r', encoding='utf-8') as injectFile:
FileNotFoundError: [Errno 2] No such file or directory: '_global.css'
```

**Comment by Doodlinka** [comment]
Same issue; deleted _global.css and now it complains about _global.html instead. Has a fix been found?
